---
- hosts: all
  roles:
    - role: andrewrothstein.docker-binaries
    - role: '{{ playbook_dir }}'
  tasks:
    - command: docker compose version
      register: docker_compose_test_output
    - name: docker compose version
      debug:
        msg: '{{ docker_compose_test_output.stdout }}'
