---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/docker-compose --version
      register: docker_compose_test_output
    - name: docker-compose --version
      debug:
        msg: '{{ docker_compose_test_output.stdout }}'
