---
- name: downloading docker-compose...
  become: yes
  become_user: root
  get_url:
    url: '{{docker_compose_url}}'
    dest: '{{docker_compose_install_dir}}/{{docker_compose_install_exe}}'
    checksum: '{{docker_compose_checksum}}'
    mode: 0755

- name: link /usr/local/bin/docker-compose
  become: yes
  become_user: root
  file:
    src: '{{docker_compose_install_dir}}/{{docker_compose_install_exe}}'
    dest: '{{docker_compose_install_dir}}/docker-compose'
    state: link
